spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB   # used to set up file upload size
springdoc:
  default-produces-media-type: application/json
server:
  servlet:
    context-path: /api/v1/
